### ISSUE TITLE
html rendering of json-ld vocabulary

### ISSUE THREAD

**Issue by onthebreeze** [edi3/edi3-json-ld-ndr#31]
Lets make the prototype HTML viewer current at https://edi3.org/vocab/# a little more usable

Here is a suggested layout for a slightly more dynamic experience https://balsamiq.cloud/s20xhay/prahay6 - although this is still implemented as a static HTML/JS website rendered from the raw json-ld vocabularies.

![Class view - tables](https://user-images.githubusercontent.com/13426392/91741727-796fac80-ebf8-11ea-8411-dbfd948c2455.png)

I've only show the table view for the class type.  there are for object types

* rdfs: class
* rdfs:property
* what "type" is a code list?
* what "type" is a code value

there are also three types of view

* table
* raw json-ld
* graph visualiser - probably using a plugin like https://github.com/science-periodicals/jsonld-vis

**Comment by kshychko** [comment]
most of the scope for this ticket has been implemented, let's close it and in case of additional work raise new tickets.
