### ISSUE TITLE
Replace rdfs:domain with schema:domainIncludes

### ISSUE THREAD

**Issue by Fak3** [edi3/edi3-json-ld-ndr#37]
By the rdfs definition, specifying multiple _rdfs:domain_ for the property means that property can only appear on a node, which must be an instance of **ALL** specified classes. But the way we generate the vocabulary requires us to define that property can appear on a node, which is an instance of  **ANY**  of the specified domain classes.

E.g. this is incorrect:
```json
     {
            "@id": "edi3:RelevantTradeParty",
            "@type": "rdfs:Property",
            "rdfs:domain": [
                "edi3:TradeSettlement",
                "edi3:TradeAgreement"
            ],
    }
```
We should replace _rdfs:domain_ with _schema:domainIncludes_ to express the optionality of the choice.

We should do the same for range - replace _rdfs:range_ with _schema:rangeIncludes_

**Comment by kshychko** [comment]
@Fak3 , please review the updated vocabulary - https://github.com/edi3/edi3.github.io/blob/bsp-update/_data/bsp.json
It is a part of PR and will be merged soon.

In addition to using _schema:domainIncludes_ and _schema:rangeIncludes_ I updated the prefix from _edi3_ to _unece_ to align with the guidance.
Also I added "unece:status" set to "deprecated" for the BIEs/ASBIEs that have Publication Comment starting with "Deprecated. Publication comments, if they are not empty now added to the _rdfs:comment_

**Comment by Fak3** [comment]
Done. Closing.
