### ISSUE TITLE
HTML Rendering of JSON-LD - adding context filters and other improvements.

### ISSUE THREAD

**Issue by onthebreeze** [edi3/edi3-json-ld-ndr#38]
The current rendering at https://edi3.org/vocabulary/bsp/ looks pretty good.  Just a few more things to improve:

## Context filters.

consider https://edi3.org/vocabulary/bsp/#Consignment

* It shows all properties of consignment.  
* But if you look at CEFACT properties you see there is "cefact:SupplyChain_Consignment.Details" and "cefact:Referenced_SupplyChain_Consignment.Details".  These two have different context specific subsets of properties and relationships of the parent "consignment"
* we want to be able to see the relevant subset of properties and relationships for each context..

## Layout changes

We also would like to slightly re-order the layout of properties, CEFACT data etc.

* above the properties list - have a line saying "Showing properties for : [drop-down with options "all contexts", and the @id of each.  Show whichever properties / relationships / referenced by are relevant for the selected context
* rename "range for" to "referenced by"
* re-order the groups : properties, relationships, referenced by, CEFACT element data

## Markup

something like this

![BSP-RDM-JSON-LD-Vocabulary-edi3-Standards-by-edi3 (1)](https://user-images.githubusercontent.com/13426392/93435598-01e69080-f90d-11ea-80db-f467ffaa1f18.png)

**Comment by kshychko** [comment]
@webilhan, filters seem to be working, but not the list population for properties/relationships.
For example, [Parameter](https://edi3.org/vocabulary/bsp/#Parameter) class has fewer properties than expected, [valueMeasure](https://edi3.org/vocabulary/bsp/#valueMeasure) is missing, although it has Parameter among domains.

**Comment by kshychko** [comment]
> @webilhan, filters seem to be working, but not the list population for properties/relationships.
> For example, [Parameter](https://edi3.org/vocabulary/bsp/#Parameter) class has fewer properties than expected, [valueMeasure](https://edi3.org/vocabulary/bsp/#valueMeasure) is missing, although it has Parameter among domains.

This has been fixed, closing the ticket.
