### ISSUE TITLE
HTML - sort list of domains

### ISSUE THREAD

**Issue by Fak3** [edi3/edi3-json-ld-ndr#40]
@kshychko Is it possible to make the list of property domain classes sorted in alphabetical order?
So that the long lists like this is easier to explore:
![Screenshot_20200928_124502](https://user-images.githubusercontent.com/991641/94417207-77adf000-0188-11eb-8a32-0efaf5b267be.jpeg)

**Comment by kshychko** [comment]
@Fak3 , this has been fixed, please verify - https://edi3.org/vocabulary/unece/#nameText

**Comment by Fak3** [comment]
fixed
