### ISSUE TITLE
NDR rules specific to Text and Identifier

### ISSUE THREAD

**Issue by nissimsan** [edi3/edi3-json-ld-ndr#43]
We are including attribute types in generating attribute names. This is needed for distinguishing for example `associatedInvoiceDiscountAmount` from `associatedInvoiceDiscountPercent`. 

However, a couple of special NDR rules will make attribute names better looking, specifically:

**`Text`, which is large redundant with the remaining part of the attribute name and should not be included in the attribute name.** (For example, `carrierProvidedInformation` is just as meaningful as `carrierProvidedInformationText`, "Text" and "Information" being basically redundant. Same thing with `damageRemarksText` where `damageRemarks` is just as descriptive).

**`Identifier`, which should just be shortened to `Id`.** (For example `freightForwarderAssignedIdentifier` would become `freightForwarderAssignedId`, "Id" is just a common shorthand, the semantic meaning is entirely preserved).

**Comment by kshychko** [comment]
@nissimsan, the vocabulary has been updated with this NDR - https://edi3.org/vocabulary/unece/#carrierProvidedInformation

**Comment by nissimsan** [comment]
Thank you @kshychko !
