### ISSUE TITLE
Link edi3 vocabulary terms to the legacy CEFACT terms by UN id

### ISSUE THREAD

**Issue by Fak3** [edi3/edi3-json-ld-ndr#8]
For those developers coming from the legacy CEFACT background it would be useful to have a way to learn the exact mapping of the class or property from the BSP/MMT Reference Data Model to the class or property in the edi3 vocabulary.

I propose we add _edi3:cefactID_ property to our vocabulary. This property will be used to associate class or property with the Unique UN Assigned ID:
```json
{
      "@id": "edi3:FinancialInstitutionAddress",
      "@type": "rdfs:Class",
      "rdfs:comment": "The location at which a financial institution may be found or reached.",
      "rdfs:label": "Financial Institution_ Address. Details",
      "edi3:cefactID": "UN01003173"
}
```

related to #4

**Comment by nissimsan** [comment]
@Fak3, I fail to understand the use case where this cefactID would be useful?

**Comment by onthebreeze** [comment]
I think the use case is vocabulary governance, not vocabulary usage.  I've no doubt that we'll refine the NDR to make the target naming as clean as possible for example we might find rules to elimiate un-necessary verbosity in names so ```@id: "edi3:ConsignmentItemQuantity",``` becomes ```@id: "edi3:ReferencedConsignmentConsignmentItemQuantity",```.  But governance processes that accept feedback on the published output still need to be traceable back to the governed source.  

for example - someone gives feedback on the publsihed output ```@id: "edi3:ConsignmentItemQuantity"```.  But back int he RDM there are duplicates that we have eliminated - so they might say - "nice, but did you mean:

* @id: "edi3:ReferencedConsignmentConsignmentItemQuantity",  or 
* @id: "edi3:SuuplyChainConsignmentConsignmentItemQuantity", ?

much simpler if the feedback includes edi3:cefactID: "UN01004196"

**Comment by nissimsan** [comment]
Agreed, @onthebreeze. 
Also, https://github.com/edi3/edi3-json-ld-ndr/issues/9 alone qualifies this requirement.

**Comment by Fak3** [comment]
We chose approach described in #12 to add UN/CEFACT metadata. Closing.
